candidate_list_full = [
    ['Greg Kwedar', 'in Fort Worth , USA', 'American director, screenwriter, and film producer'],
    ['Vanessa Ossa', '1981 in Bochum , Germany', 'is a German media scientist'],
    ['Corey Mylchreest', 'May 8, 1998, in London, England, UK', 'is a British actor'],
    ['Demi Moore', 'November 11, 1962, in Roswell, New Mexico, USA', 'is an American actress'],
    ['Albert Einstein', 'March 14, 1879, in Ulm, Germany','was a theoretical physicist'],
    ['Beyoncé Giselle Knowles', 'September 4, 1981, in Houston, Texas, USA','is an American R&B and pop singer and actress'],
    ['Till Timmermann', '1995, in Göttingen, Germany', 'is a German actor'],
    ['Snowden', 'June 21, 1983, in Elizabeth City, North Carolina, USA', 'is an American-Russian whistleblower, computer nerd, NSA'],
    ['Wilhelm Barthlott', 'June 22, 1946, in Forst, Germany','is a German botanist, bionics researcher, and materials scientist'],
    ['Ángel Encinas Bardem', 'March 1, 1969, in Las Palmas de Gran Canaria, Spain', 'is an internationally renowned and award-winning Spanish actor'],
    ['Dukes', 'August 4, 1961, in Inkster, Michigan, USA, America', 'is a former American basketball player'],
    ['Julien Abardonado', 'May 27, 1978, in Marseille, France', 'is a French football player'],
    ['William Heath Robinson', 'May 31, 1872, in London, England', 'was a British cartoonist, illustrator, writer, and stage designer'],
    ['Otto Hagel', 'March 12, 1909, in Fellbach as Otto Hägele, Germany', 'was a German-born American photographer and filmmaker'],
    ['Jon Walter Nonni Ardal Hammarström', 'August 25, 2001, in Stockholm, Sweden', 'is a Swedish actor'],
    ['Lady du Maurier', 'April 14, 1881, England', 'was a British stage actress'],
    ['Sir Salvador Moncada', 'December 3, 1944, in Tegucigalpa, Honduras', 'is a British-Honduran pharmacologist'],
    ['Sandra Droucker', 'May 7, 1875, in Saint Petersburg, Russia','was a Russian-Norwegian pianist and music educator'],
    ['Miguel Covarrubias Duclaud', 'November 22, 1904, in Mexico City, Mexico', 'also known as "El Chamaco" (Spanish nickname, information incomplete)'],
    ['Sir Richard Arkwright', 'December 23, 1732, in Preston, Lancashire, England', 'was a wealthy textile industrialist and inventor who held numerous spinning-related patents'],
    ['Kip Stephen Thorne', 'June 1, 1940, in Logan, Utah, USA, America', 'is an American theoretical physicist'],
    ['Funda Rosenland', 'March 5, 1979, in Cologne, Germany', 'is a German-Turkish actress'],
    ['Sir Bernard Henry Spilsbury', 'May 16, 1877, in Leamington Spa, Warwickshire, England',  'was a British pathologist and forensic scientist'],
    ['Mike Skinner', 'November 27, 1978, in London-Barnet, England', 'is an English rapper, musician, and producer best known for his rap project The Streets'],
    ['Friedrich August Hayek', 'May 8, 1899, in Vienna, Austria', 'was an Austrian economist and social philosopher'],
    ['Johann Konrad Kern', 'June 11, 1808, in Berlingen TG, Switzerland', 'was a Swiss jurist and National Councillor from the canton of Thurgau'],
    ["Matt Loughrey", "1979, Ireland", "is an Irish artist known for coloring historical figures, photographs, and films"],
    ['Britney Jean Spears', 'December 2, 1981, in McComb, Mississippi, USA, America', 'is an American pop singer'],
    ['Michael Nip Hall', 'June 12, 1953, in Puerto Rico',' is an American-Swiss molecular biologist and professor at the Biozentrum of the University of Basel'],
    ['Sarah Casado Thomas', 'July 2, 1981, in Madrid, Spain', 'is a German-Spanish actress in film, television, and theater, model, speaker, and voice actor'],
    ['KBE', 'March 11, 1890, in Everett, Massachusetts, USA, America', 'was an American engineer and pioneer of analog computing'],
    ["Hedwig Blesi", "December 21, 1869 in Zurich, Switzerland", "was a Swiss educator and dialect writer"],
    ['Jeremy Michael Jordan', 'November 20, 1984, in Corpus Christi, Texas, USA', 'is an American actor, musical performer, singer, and musician'],
    ['Amell', 'April 21, 1988, in Toronto, Ontario, Canada', 'is a Canadian-American actor and film producer'],
    ['Jil Devresse', 'August 9, 1997,  Luxembourg', 'is a Luxembourgish-German actress'],
    ["Kim Newman", "July 31, 1959 in London, United Kingdom, England", "is a British film critic, journalist, and horror genre writer"],
    ['Hans Elias', 'June 28, 1907, in Darmstadt,Germany','was a German-American scientist and artist who emigrated to Italy in 1935 and then to the USA'],
    ['Barrak Hussein Obama','1956, America, USA','President'],
    ['Michael Jeffrey Jordan', '(born February 17, 1963) in USA', 'also known by his initials MJ,[9] is an American businessman and former professional basketball player.'],
    ['Paul Thomas Mann', '6 June 1875 in Germany', 'was a German novelist, short story writer, social critic, philanthropist, essayist, and the 1929 Nobel Prize in Literature laureate'],
    ['Napoleon Bonaparte', '15 August 1769 in France', 'was a French general and statesman'],['Christopher Columbus', '(born 25 August 1451) in Italy', 'explorer and navigator.'],
    ['Leonardo da Vinci', '15 April 1452 in Italy', 'was a polymath, painter, engineer, scientist, and inventor'],
    ['Mozart (Wolfgang Amadeus Mozart)', '27 January 1756 in Austria', 'was a composer of the Classical period, known for his symphonies, operas, and chamber music'],
    ['William Shakespeare', '26 April 1564 (baptized) in England', 'was a playwright, poet, and actor, widely regarded as the greatest writer in the English language']
]